// state yönetiminde kullanılan sabitler

export const RESERVATION_ADD_REQUEST = 'RESERVATION_ADD_REQUEST';
export const RESERVATION_ADD_SUCCESS = 'RESERVATION_ADD_SUCCESS';
export const RESERVATION_ADD_FAIL = 'RESERVATION_ADD_FAIL';

export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST';
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS';
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL';

export const FLIGHT_LIST_REQUEST = 'FLIGHT_LIST_REQUEST';
export const FLIGHT_LIST_SUCCESS = 'FLIGHT_LIST_SUCCESS';
export const FLIGHT_LIST_FAIL = 'FLIGHT_LIST_FAIL';

export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_SELECTED_FLIGHT = 'SET_SELECTED_FLIGHT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SHOW_CONFIRMATION = 'SHOW_CONFIRMATION';
export const SET_COUNTDOWN = 'SET_COUNTDOWN';
export const SET_USERNAME = 'SET_USERNAME';

export const SET_FILTER_CRITERIA = 'SET_FILTER_CRITERIA';